#!/usr/bin/env bash
set -euo pipefail

TMAX_DIR=recipe/tmax

MODEL_PATH="${MODEL_PATH:-Qwen/Qwen3.5-9B}"
TRAIN_FILES="${TRAIN_FILES:-${HOME}/data/tmax/train.parquet}"
VAL_FILES="${VAL_FILES:-${HOME}/data/tmax/val.parquet}"
PROJECT_NAME="${PROJECT_NAME:-tmax}"
EXPERIMENT_NAME="${EXPERIMENT_NAME:-qwen35-9b-dppo-tv}"
CHECKPOINT_DIR="${CHECKPOINT_DIR:-checkpoints/${PROJECT_NAME}/${EXPERIMENT_NAME}}"

MAX_PROMPT_LENGTH=2048
MAX_RESPONSE_LENGTH=65536
MAX_MODEL_LEN=$((MAX_PROMPT_LENGTH + MAX_RESPONSE_LENGTH))
SP_SIZE=4
MAX_TOKEN_LEN_PER_GPU=$((MAX_MODEL_LEN / SP_SIZE))

python3 -m verl.trainer.main_ppo \
    model_engine=dp \
    algorithm.adv_estimator=grpo \
    algorithm.norm_adv_by_std_in_grpo=False \
    algorithm.use_kl_in_reward=False \
    algorithm.rollout_correction.bypass_mode=True \
    algorithm.filter_groups.enable=True \
    algorithm.filter_groups.metric=acc \
    data.train_files="['${TRAIN_FILES}']" \
    data.val_files="['${VAL_FILES}']" \
    data.train_batch_size=8 \
    data.max_prompt_length=${MAX_PROMPT_LENGTH} \
    data.max_response_length=${MAX_RESPONSE_LENGTH} \
    data.return_raw_chat=True \
    data.filter_overlong_prompts=True \
    actor_rollout_ref.hybrid_engine=False \
    actor_rollout_ref.model.path="${MODEL_PATH}" \
    +actor_rollout_ref.model.override_config.attn_implementation=flash_attention_3 \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.model.use_fused_kernels=True \
    actor_rollout_ref.model.fused_kernel_options.impl_backend=triton \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.strategy=fsdp2 \
    actor_rollout_ref.actor.fsdp_config.use_no_sync_for_gradient_accumulation=False \
    actor_rollout_ref.actor.fsdp_config.offload_policy=False \
    actor_rollout_ref.actor.fsdp_config.ulysses_sequence_parallel_size=${SP_SIZE} \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.actor.optim.lr_scheduler_type=constant \
    actor_rollout_ref.actor.optim.lr_warmup_steps=0 \
    actor_rollout_ref.actor.optim.clip_grad=1.0 \
    actor_rollout_ref.actor.optim.weight_decay=0.0 \
    actor_rollout_ref.actor.ppo_mini_batch_size=8 \
    actor_rollout_ref.actor.use_kl_loss=False \
    actor_rollout_ref.actor.entropy_coeff=0.0 \
    actor_rollout_ref.actor.policy_loss.loss_mode=dppo_tv \
    actor_rollout_ref.actor.clip_ratio_low=0.1 \
    actor_rollout_ref.actor.clip_ratio_high=0.1 \
    actor_rollout_ref.actor.clip_ratio_c=1.0e9 \
    actor_rollout_ref.actor.loss_agg_mode=token-mean \
    actor_rollout_ref.actor.use_dynamic_bsz=True \
    actor_rollout_ref.actor.ppo_max_token_len_per_gpu=${MAX_TOKEN_LEN_PER_GPU} \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.mode=async \
    actor_rollout_ref.rollout.n=32 \
    actor_rollout_ref.rollout.temperature=1.0 \
    actor_rollout_ref.rollout.top_p=1.0 \
    actor_rollout_ref.rollout.calculate_log_probs=True \
    actor_rollout_ref.rollout.max_model_len=${MAX_MODEL_LEN} \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.8 \
    +actor_rollout_ref.rollout.engine_kwargs.vllm.gdn_prefill_backend=triton \
    +actor_rollout_ref.rollout.engine_kwargs.vllm.hf_overrides.head_dtype=float32 \
    actor_rollout_ref.rollout.log_prob_use_dynamic_bsz=True \
    actor_rollout_ref.rollout.log_prob_max_token_len_per_gpu=${MAX_TOKEN_LEN_PER_GPU} \
    actor_rollout_ref.rollout.checkpoint_engine.backend=nccl \
    actor_rollout_ref.rollout.checkpoint_engine.update_weights_bucket_megabytes=1024 \
    actor_rollout_ref.rollout.nnodes=6 \
    actor_rollout_ref.rollout.n_gpus_per_node=8 \
    actor_rollout_ref.rollout.val_kwargs.n=4 \
    actor_rollout_ref.rollout.val_kwargs.temperature=0.6 \
    actor_rollout_ref.rollout.val_kwargs.top_p=0.95 \
    actor_rollout_ref.rollout.multi_turn.enable=True \
    actor_rollout_ref.rollout.multi_turn.max_assistant_turns=64 \
    actor_rollout_ref.rollout.multi_turn.tool_config_path="${TMAX_DIR}/tools.yaml" \
    actor_rollout_ref.rollout.multi_turn.format=qwen3_coder \
    actor_rollout_ref.rollout.agent.agent_loop_config_path="${TMAX_DIR}/agent_loop.yaml" \
    actor_rollout_ref.rollout.agent.default_agent_loop=tmax_agent \
    trainer.use_v1=True \
    trainer.v1.trainer_mode=separate_async \
    trainer.v1.separate_async.num_warmup_batches=4 \
    trainer.v1.separate_async.parameter_sync_step=1 \
    trainer.v1.sampler.max_off_policy_threshold=5 \
    trainer.v1.sampler.max_off_policy_strategy=drop \
    trainer.project_name="${PROJECT_NAME}" \
    trainer.experiment_name="${EXPERIMENT_NAME}" \
    trainer.logger='["console","wandb"]' \
    trainer.nnodes=2 \
    trainer.n_gpus_per_node=8 \
    trainer.val_before_train=True \
    trainer.save_freq=20 \
    trainer.test_freq=20 \
    trainer.total_epochs=1 \
    trainer.total_training_steps=500 \
    trainer.default_local_dir="${CHECKPOINT_DIR}" \
    transfer_queue.enable=True \
    "$@"
