#!/bin/bash

python3 -m verl.trainer.main_ppo \
      --config-path=/home/verl/examples/vllm_multiturn/config \
      --config-name='gsm8k_multiturn_grpo' \
      algorithm.adv_estimator=grpo \
      data.train_batch_size=16 \
      data.max_prompt_length=1024 \
      data.max_response_length=1024 \
      data.filter_overlong_prompts=True \
      data.truncation='error' \
      data.return_raw_chat=True \
      actor_rollout_ref.model.path=/var/model/Qwen2.5-3B-Instruct \
      actor_rollout_ref.actor.optim.lr=1e-6 \
      actor_rollout_ref.model.use_remove_padding=True \
      actor_rollout_ref.actor.ppo_mini_batch_size=8 \
      actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=1 \
      actor_rollout_ref.actor.use_kl_loss=True \
      actor_rollout_ref.actor.kl_loss_coef=0.001 \
      actor_rollout_ref.actor.kl_loss_type=low_var_kl \
      actor_rollout_ref.actor.entropy_coeff=0 \
      actor_rollout_ref.model.enable_gradient_checkpointing=True \
      actor_rollout_ref.actor.fsdp_config.param_offload=False \
      actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
      actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=1 \
      actor_rollout_ref.rollout.tensor_model_parallel_size=2 \
      actor_rollout_ref.rollout.name=vllm \
      actor_rollout_ref.rollout.mode=async \
      actor_rollout_ref.rollout.gpu_memory_utilization=0.5 \
      actor_rollout_ref.rollout.n=16 \
      actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=1 \
      actor_rollout_ref.ref.fsdp_config.param_offload=True \
      actor_rollout_ref.rollout.trace.backend=mlflow \
      actor_rollout_ref.rollout.trace.token2text=True \
      algorithm.use_kl_in_reward=False \
      trainer.critic_warmup=0 \
      trainer.logger='["console","mlflow"]' \
      trainer.project_name='gsm8k_tool-agent' \
      trainer.experiment_name='qwen2.5-3b_function_rm-gsm8k-vllm-tool-agent-verify-n16' \
      trainer.n_gpus_per_node=8 \
      trainer.nnodes=1 \
      trainer.save_freq=1 \
      trainer.test_freq=20 \
      trainer.total_training_steps=1 \
      data.train_files=/var/model-dataset/processed-gsm8k/train20.parquet \
      data.val_files=/var/model-dataset/processed-gsm8k/test100.parquet \
      actor_rollout_ref.rollout.multi_turn.tool_config_path="/home/verl/examples/vllm_multiturn/config/tool_config/gsm8k_mcp_tool_config.yaml" \
      actor_rollout_ref.actor.checkpoint.save_contents='["hf_model", "model"]' \
      trainer.total_epochs=1 